spring:
    profiles: dev
serviceNowConfiguration:
    instanceUrl: https://dev34384.service-now.com
    username: admin
    password: admin
ecsConfiguration:
    ecsMgmtAccessKey: AIzaSyAWNS39cnGHhvrzyJqTzjsoa_QUuL4frd4
    ecsMgmtSecretKey: 491126193419-8nefef40b8osi6spv7omhdg8airt8icn.apps.googleusercontent.com
    ecsMgmtPort: 4443
    hosts: 192.168.0.100

---
spring:
    profiles: prod
servicenowConfiguration:
    instanceUrl: https://dev34384.service-now.com
    username: admin
    password: root
ecsConfiguration:
    ecsMgmtAccessKey: AIzaSyAWNS39cnGHhvrzyJqTzjsoa_QUuL4frd4
    ecsMgmtSecretKey: 491126193419-8nefef40b8osi6spv7omhdg8airt8icn.apps.googleusercontent.com
    ecsMgmtPort: 4443
    hosts: 192.168.0.100